version: "3.9"
services:
  symbolic:
    build: .
    container_name: symbolic
    command: python symbolic/main.py
    volumes:
      - .:/app

  numeric:
    build: .
    container_name: numeric
    command: python numeric/main.py
    volumes:
      - .:/app

  visualization:
    build: .
    container_name: visualization
    command: python visualization/app.py
    ports:
      - "8050:8050"
    volumes:
      - .:/app
